### ISSUE TITLE
Connection failed.

### ISSUE THREAD

**Issue by boustanihani** [DrMongo/DrMongo#103]
I am always getting `Connection failed.` when trying to connect to my database on compose, there is no useful output on the consoles (server+client) ... I checked the Mongo-URI several times. I have an elastic deployment (2 replica nodes + 1 backup node)

**Comment by boustanihani** [comment]
I just update DrMongo and now I am getting the following, my auth credentials are 100% correct:

```
I20151203-06:17:32.747(0)? > connection error:  { [MongoError: Authentication failed.]
I20151203-06:17:32.747(0)?   name: 'MongoError',
I20151203-06:17:32.749(0)?   ok: 0,
I20151203-06:17:32.749(0)?   code: 18,
I20151203-06:17:32.749(0)?   errmsg: 'Authentication failed.' }
I20151203-06:17:32.749(0)? -----
I20151203-06:17:32.907(0)? Exception while invoking method 'updateConnectionStructure' MongoError: Authentication failed.
I20151203-06:17:32.907(0)?     at Object.Future.wait (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.10.10r2s24++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151203-06:17:32.907(0)?     at packages/meteor/helpers.js:119:1
I20151203-06:17:32.907(0)?     at Object.MongoHelpers.getDatabases (server/MongoHelpers.js:24:14)
I20151203-06:17:32.908(0)?     at [object Object].Meteor.methods.updateConnectionStructure (server/methods.js:18:34)
I20151203-06:17:32.908(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151203-06:17:32.908(0)?     at livedata_server.js:708:19
I20151203-06:17:32.908(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151203-06:17:32.908(0)?     at livedata_server.js:706:40
I20151203-06:17:32.908(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151203-06:17:32.909(0)?     at livedata_server.js:704:46
I20151203-06:17:32.909(0)?     at tryCallTwo (/home/ubuntu/.meteor/packages/promise/.0.5.1.11b2v66++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151203-06:17:32.909(0)?     at doResolve (/home/ubuntu/.meteor/packages/promise/.0.5.1.11b2v66++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151203-06:17:32.909(0)?     at new Promise (/home/ubuntu/.meteor/packages/promise/.0.5.1.11b2v66++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151203-06:17:32.909(0)?     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
I20151203-06:17:32.909(0)?     at livedata_server.js:548:43
I20151203-06:17:32.910(0)?     - - - - -
I20151203-06:17:32.910(0)?     at Object.toError (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20151203-06:17:32.910(0)?     at /home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1196:31
I20151203-06:17:32.910(0)?     at /home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
I20151203-06:17:32.910(0)?     at Server.Base._callHandler (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20151203-06:17:32.931(0)?     at /home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
I20151203-06:17:32.931(0)?     at [object Object].MongoReply.parseBody (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20151203-06:17:32.931(0)?     at [object Object].<anonymous> (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
I20151203-06:17:32.932(0)?     at [object Object].emit (events.js:95:17)
I20151203-06:17:32.932(0)?     at [object Object].<anonymous> (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
I20151203-06:17:32.932(0)?     at [object Object].emit (events.js:98:17)
I20151203-06:17:32.932(0)?     at Socket.<anonymous> (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.14ovq3s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
I20151203-06:17:32.932(0)?     at Socket.emit (events.js:95:17)
I20151203-06:17:32.933(0)?     at Socket.<anonymous> (_stream_readable.js:765:14)
I20151203-06:17:32.933(0)?     at Socket.emit (events.js:92:17)
I20151203-06:17:32.933(0)?     at emitReadable_ (_stream_readable.js:427:10)
I20151203-06:17:32.933(0)?     at emitReadable (_stream_readable.js:423:5)
I20151203-06:17:32.933(0)?     at readableAddChunk (_stream_readable.js:166:9)
I20151203-06:17:32.934(0)?     at Socket.Readable.push (_stream_readable.js:128:10)
I20151203-06:17:32.934(0)?     at TCP.onread (net.js:529:21)
```

**Comment by achtan** [comment]
hi, pls pull new version, and let me know if it is working

**Comment by boustanihani** [comment]
Now there are no errors thrown, but I can't see any colections...

**Comment by tothradoslav** [comment]
When in list of "connections", click the "refresh" button by that connection. Let me know if this "fetched" all the collections. Thanks.

**Comment by boustanihani** [comment]
sadly nothing happens, even no error messages...

**Comment by boustanihani** [comment]
Here is a test deployment with a test database =>

Test deployment: http://drmongo1.meteor.com/mongolab

Test database: `mongodb://doctor:mongo@ds055722.mongolab.com:55722/drmongo1`

**Comment by achtan** [comment]
I added more detailed error reporting in current master.

So now i getting this error (in console) `not authorized on admin to execute command { listDatabases: 1 }`. Can you please check if it is possible to enable command `listDatabases` on Compose. Meanwhile i will work on workaround.

**Comment by achtan** [comment]
try it pls now... its working for me, now i only getting error with ObjectID #110

**Comment by boustanihani** [comment]
@achtan I confirm your observation

**Comment by tothradoslav** [comment]
yep, working on the ObjectID issue, but kind of stuck. Will welcome any ideas, guys...

**Comment by achtan** [comment]
ObjectID support is implemented, check it out! :)
