### ISSUE TITLE
Not finding documents but collections are working

### ISSUE THREAD

**Issue by JeremyBYU** [DrMongo/DrMongo#106]
Hey I am getting this error: double colon in host identifier.  However the connection seems to be working.  It brings up the database and sees my collections.  It just cant find the documents.

url: mongodb://localhost:3001
Windows 10
Meteor 1.2

```
I20151201-23:15:16.935(-6)? Exception while invoking method 'getDocuments' Error: double colon in host identifier
I20151201-23:15:16.936(-6)?     at module.exports (C:\Users\Jeremy\Documents\webdevelopment\Meteor\DrMongo\.meteor\local\isopacks\npm-container\npm\node_modules\mongodb\lib\url_parser.js:91:13)
I20151201-23:15:16.936(-6)?     at connect (C:\Users\Jeremy\Documents\webdevelopment\Meteor\DrMongo\.meteor\local\isopacks\npm-container\npm\node_modules\mongodb\lib\mongo_client.js:125:16)
I20151201-23:15:16.936(-6)?     at MongoClient.connect (C:\Users\Jeremy\Documents\webdevelopment\Meteor\DrMongo\.meteor\local\isopacks\npm-container\npm\node_modules\mongodb\lib\mongo_client.js:109:3)
I20151201-23:15:16.936(-6)?     at packages/meteor/helpers.js:118:1
I20151201-23:15:16.936(-6)?     at connectDatabase (lib/helpers.js:9:11)
I20151201-23:15:16.936(-6)?     at [object Object].Meteor.methods.getDocuments (server/methods.js:97:14)
I20151201-23:15:16.936(-6)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151201-23:15:16.937(-6)?     at livedata_server.js:708:19
I20151201-23:15:16.937(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151201-23:15:16.937(-6)?     at livedata_server.js:706:40
I20151201-23:15:16.937(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151201-23:15:16.937(-6)?     at livedata_server.js:704:46
I20151201-23:15:16.937(-6)?     at tryCallTwo (C:\Users\Jeremy\AppData\Local\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:45:5)
I20151201-23:15:16.937(-6)?     at doResolve (C:\Users\Jeremy\AppData\Local\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:171:13)
I20151201-23:15:16.937(-6)?     at new Promise (C:\Users\Jeremy\AppData\Local\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:65:3)
I20151201-23:15:16.937(-6)?     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
I20151201-23:15:16.938(-6)?     at livedata_server.js:548:43
```

**Comment by lynchem** [comment]
+1 
Exact same except running OSX 10.11

**Comment by achtan** [comment]
sorry guys I cannot reproduce the error, but I did some changes in code. Can you please update your Dr. Mongo a try it again. thx

**Comment by spacenergy** [comment]
![2015-12-02 18-26-46 drmongo node node](https://cloud.githubusercontent.com/assets/2149707/11530867/5815f45a-9922-11e5-9b2b-a39d82b6ccbc.png)

**Comment by spacenergy** [comment]
![2015-12-02 18-30-23 feedback find page 1 dr mongo](https://cloud.githubusercontent.com/assets/2149707/11530914/c760004e-9922-11e5-9966-b3ccc16f6af8.png)

**Comment by achtan** [comment]
hi @spacenergy do you have latest version of Dr. Mongo? on which page you are on when this error triggers?

**Comment by spacenergy** [comment]
I don't speak english, sorry

![2015-12-02 18-56-12 drmongo node node](https://cloud.githubusercontent.com/assets/2149707/11531376/a16a7c12-9926-11e5-8861-96bb571dc0c8.png)

**Comment by tothradoslav** [comment]
I think I found the issue. Please try now.

**Comment by JeremyBYU** [comment]
Its working for me.  Thanks!

**Comment by spacenergy** [comment]
Now everything is fine, thank you!
